# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9ddea887a196ba5312067a9c5081e83cf2888703fcf811a48797c27b439f4a3042be5f0c56804ea77d68455ab8fb53e2c084b2f093cda38467c7246387ecb340

test:
  secret_key_base: 4186ca0e4657450d8abe96d7390973a242b167f55fe19cacd2b4d02dd1f56381c256acb22dbb633d8d2acfca52e64bb8a4f815e5711af7e33146fceef16a15e2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
